/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_SLAVEMESSAGE_PB_H_INCLUDED
#define PB_SLAVEMESSAGE_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SlaveDetails {
    pb_callback_t id;
    pb_callback_t mac;
} SlaveDetails;

typedef struct _SlaveMessage {
    bool has_slave;
    SlaveDetails slave;
    uint32_t seq;
    pb_callback_t data;
} SlaveMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SlaveMessage_init_default                {false, SlaveDetails_init_default, 0, {{NULL}, NULL}}
#define SlaveDetails_init_default                {{{NULL}, NULL}, {{NULL}, NULL}}
#define SlaveMessage_init_zero                   {false, SlaveDetails_init_zero, 0, {{NULL}, NULL}}
#define SlaveDetails_init_zero                   {{{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SlaveDetails_id_tag                      1
#define SlaveDetails_mac_tag                     2
#define SlaveMessage_slave_tag                   1
#define SlaveMessage_seq_tag                     2
#define SlaveMessage_data_tag                    3

/* Struct field encoding specification for nanopb */
#define SlaveMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  slave,             1) \
X(a, STATIC,   SINGULAR, UINT32,   seq,               2) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              3)
#define SlaveMessage_CALLBACK pb_default_field_callback
#define SlaveMessage_DEFAULT NULL
#define SlaveMessage_slave_MSGTYPE SlaveDetails

#define SlaveDetails_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   id,                1) \
X(a, CALLBACK, SINGULAR, STRING,   mac,               2)
#define SlaveDetails_CALLBACK pb_default_field_callback
#define SlaveDetails_DEFAULT NULL

extern const pb_msgdesc_t SlaveMessage_msg;
extern const pb_msgdesc_t SlaveDetails_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SlaveMessage_fields &SlaveMessage_msg
#define SlaveDetails_fields &SlaveDetails_msg

/* Maximum encoded size of messages (where known) */
/* SlaveMessage_size depends on runtime parameters */
/* SlaveDetails_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
