/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#include "SlaveMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SlaveMessage, SlaveMessage, AUTO)


PB_BIND(SlaveDetails, SlaveDetails, AUTO)



