/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8-dev */

#ifdef DCSBIOS_ESP32_ID

#include "SlaveMessage.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SlaveMessage, SlaveMessage, AUTO)

#endif